# Generated by Django 4.2.6 on 2023-10-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortenerService', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=255, null=True, unique=True)),
                ('shortened_url', models.CharField(max_length=255, null=True, unique=True)),
                ('expiration_timestamp', models.DateTimeField()),
                ('max_usage', models.IntegerField()),
                ('uuid', models.CharField(max_length=255, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='URLShortenerService.user')),
            ],
            options={
                'unique_together': {('original_url', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ShortURLAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, null=True, unique=True)),
                ('user_agent', models.CharField(max_length=255, null=True, unique=True)),
                ('access_time', models.DateTimeField()),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='URLShortenerService.shorturl')),
            ],
        ),
    ]
