# Generated by Django 4.2.6 on 2023-10-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLShortenerService', '0003_shorturl_shorturlaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='shortened_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shorturlaccess',
            name='ip_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shorturlaccess',
            name='user_agent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
